

export type DocumentType = 'proces verbal de receptie' | 'instructiuni pentru confirmarea primirii coletului' | 'parcel inventory' | 'PV' | 'AWB' | 'Email';
export type DocumentStatus = 'Not Generated' | 'Generated' | 'Failed' | 'Complet' | 'Queued';

export type RecipientStatus = 
  | 'New'
  | 'Documents Generated'
  | 'Delivered'
  | 'Completed'
  | 'Returned';

export type ExpeditionStatus = 
  | 'New'
  | 'Ready for AWB'
  | 'AWB Generation Queued'
  | 'AWB Generated'
  | 'AWB Generation Failed'
  | 'Sent to Logistics'
  | 'Email Send Failed'
  | 'In Transit'
  | 'Delivered' 
  | 'Canceled'
  | 'Lost or Damaged'
  | 'Completed';


export interface Document {
    status: DocumentStatus;
    content?: string;
    url?: string;
    fileId?: string;
    error?: string;
}

export interface Recipient {
  id: string; // The unique Firestore document ID
  numericId: string; // The original ID from the imported file (destinatar_id)
  uuid?: string; // A new, autogenerated UUID for each recipient
  shipmentId: string; // id_unic_expeditie
  awbId: string; // The ID of the AWB document this recipient belongs to
  name: string; // Nume și prenume
  status: RecipientStatus;
  
  // Document fields
  pvStatus?: DocumentStatus;
  pvId?: string; 
  pvUrl?: string; 
  pvSemnatUrl?: string;
  
  inventoryStatus?: DocumentStatus;
  inventoryUrl?: string;
  inventoryFileId?: string;

  instructionsStatus?: DocumentStatus;
  instructionsUrl?: string;
  instructionsFileId?: string;
  
  awbStatus?: DocumentStatus;
  awbUrl?: string;

  group?: string;
  schoolName?: string; // from 'location'
  schoolUniqueName?: string; // from 'COD UNIC'
  email?: string;
  telephone?: string; // from 'phone'
  awbWebviewUrl?: string;
  awbPdfFileId?: string;
}

export type AWBStatus = 'New' | 'Queued' | 'Generated' | 'Failed' | 'AWB_CREATED';
export type EmailStatus = 'Sent' | 'Failed' | 'Not Sent';

export interface ExpeditionStatusInfo {
  statusId: number;
  status: string;
  statusLabel: string;
  statusState: string;
  statusDate: string;
  county: string;
  parcelAwbNumber: string | null;
  reasonId: number | null;
  reason: string;
  parcelDetails: any | null;
  expeditionDetails: any | null;
  transitLocation: string;
  inReturn: boolean | null;
}

export interface Note {
    id: string;
    text: string;
    userId: string;
    userName: string;
    recipientId: string;
    recipientName: string;
    createdAt: any; // Firestore Timestamp
}

export interface AWB {
    id: string; // Firestore auto-generated ID
    shipmentId: string;
    awbNumber?: string; // The number received from the courier API
    mainRecipientName: string; // Nume_awb
    mainRecipientTelephone?: string; // Nr_tel_awb
    mainRecipientEmail?: string;
    parcelCount?: number; // parcel_count
    packageSize?: string; // TIP CUTIE
    status: AWBStatus;
    error?: string | null;
    awbUrl?: string;
    awbFileId?: string; // The GDrive file ID for the AWB PDF
    emailStatus?: EmailStatus;
    emailId?: string;
    notes?: Note[];
    awb_data?: {
      awbNumber: string;
      awbCost: number;
      parcels: { position: number; awbNumber: string }[];
      pdfLink: string;
      pickupLogisticLocation: string;
      deliveryLogisticLocation: string;
      deliveryLogisticCircle: string;
      sortingHub: string;
      sortingHubId: number;
      deliveryLogisticLocationId: number;
      pickupLogisticLocationId: number;
    };
    expeditionStatus?: ExpeditionStatusInfo;
    awbStatusHistory?: ExpeditionStatusInfo[];

    // Address fields moved from Recipient
    address: string;
    city: string;
    county: string;
    postalCode?: string;
}

export interface Expedition {
  id: string; // This is the shipmentId
  status: ExpeditionStatus;
  recipientCount: number;
  awbCount: number;
  createdAt: any; // Firestore serverTimestamp
}

export interface Shipment {
    id: string;
    awbDocumentId: string;
    awbNumberOfParcels: number;
    inventoryDocumentId: string;
    instructionsDocumentId: string;
    status: ExpeditionStatus;
    // Add any other fields from your shipments collection that might be needed
}
